from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

MARKER_START = "# UI test loop (ai-assistant)"
MARKER_END = "# end ui test loop"

GITIGNORE_LINES = (
    ".agent/",
    "ui-test/.env",
    "ui-test/.env.local",
    "!ui-test/.env.example",
)

ENV_EXAMPLE = """# Copy to .env and fill in (never commit .env)

RAILWAY_TOKEN=

UI_TEST_EMAIL=
UI_TEST_PASSWORD=

# Or use ADMIN_SEED_* — the runner maps them automatically
# ADMIN_SEED_EMAIL=
# ADMIN_SEED_PASSWORD=
"""

UI_TEST_README = """# UI test (this project)

Managed by [ai-assistant](https://github.com/) `ui_test` engine. Specs and Railway config live here; reports go to `.agent/current/`.

Run from ai-assistant:

```powershell
.\\run-test-runner.ps1
# or
.\\run-ui-test.ps1 -Project {project_path}
```
"""


@dataclass(frozen=True)
class ProjectSetupResult:
    gitignore_updated: bool
    created_paths: tuple[str, ...]


def _gitignore_block() -> str:
    lines = [MARKER_START, *GITIGNORE_LINES, MARKER_END, ""]
    return "\n".join(lines)


def _block_present(text: str) -> bool:
    return MARKER_START in text and MARKER_END in text


def _replace_block(text: str, block: str) -> str:
    start = text.index(MARKER_START)
    end = text.index(MARKER_END) + len(MARKER_END)
    return text[:start] + block.rstrip() + text[end:]


def ensure_gitignore(project: Path) -> bool:
    """Ensure target project .gitignore contains UI test / .agent entries."""
    gitignore_path = project / ".gitignore"
    block = _gitignore_block()

    if gitignore_path.is_file():
        text = gitignore_path.read_text(encoding="utf-8")
        if _block_present(text):
            new_block = block.rstrip()
            existing_start = text.index(MARKER_START)
            existing_end = text.index(MARKER_END) + len(MARKER_END)
            existing_section = text[existing_start:existing_end]
            if existing_section == new_block:
                return False
            updated = _replace_block(text, block)
        else:
            suffix = "" if text.endswith("\n") else "\n"
            updated = text + suffix + "\n" + block
    else:
        updated = block

    gitignore_path.write_text(updated, encoding="utf-8")
    return True


def ensure_ui_test_tree(project: Path) -> list[str]:
    """Create minimal ui-test folders and template files if missing."""
    created: list[str] = []
    ui_test = project / "ui-test"
    dirs = [
        ui_test,
        ui_test / "specs",
        ui_test / "tasks",
    ]
    for directory in dirs:
        if not directory.is_dir():
            directory.mkdir(parents=True, exist_ok=True)
            created.append(str(directory.relative_to(project)))

    example_env = ui_test / ".env.example"
    if not example_env.is_file():
        example_env.write_text(ENV_EXAMPLE, encoding="utf-8")
        created.append(str(example_env.relative_to(project)))

    readme = ui_test / "README.md"
    if not readme.is_file():
        readme.write_text(
            UI_TEST_README.format(project_path=project),
            encoding="utf-8",
        )
        created.append(str(readme.relative_to(project)))

    tasks_file = ui_test / "tasks" / "current.txt"
    if not tasks_file.is_file():
        tasks_file.write_text(
            "Describe what you want verified on the deployed app.\n",
            encoding="utf-8",
        )
        created.append(str(tasks_file.relative_to(project)))

    agent_readme = project / ".agent" / "README.md"
    if not agent_readme.is_file():
        agent_readme.parent.mkdir(parents=True, exist_ok=True)
        agent_readme.write_text(
            "# Agent reports\n\n"
            "Generated by the UI test loop. See `.agent/current/REPORT.md` after each run.\n",
            encoding="utf-8",
        )
        created.append(str(agent_readme.relative_to(project)))

    return created


def ensure_project_setup(project: Path) -> ProjectSetupResult:
    """Update .gitignore and scaffold ui-test paths on the target project."""
    gitignore_updated = ensure_gitignore(project)
    created = ensure_ui_test_tree(project)
    return ProjectSetupResult(
        gitignore_updated=gitignore_updated,
        created_paths=tuple(created),
    )
