#!/usr/bin/env python3
"""Reset exploration/run artifacts under a target project's .agent/ folder.

Keeps project setup files (cheatsheet, specs, profile, env). Removes site map,
navigation tree, learnings, and run output so exploration starts fresh.

Usage:
  python -m ui_test.reset_agent --project ../content-manager
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from ui_test.project_paths import agent_dir

# Generated by exploration / runs — safe to delete for a fresh start.
EXPLORATION_FILES = (
    "exploration.yaml",
    "site-map.yaml",
    "site-map.json",
    "cheatsheet-navigation.yaml",
    "cheatsheet-navigation.json",
    "cheatsheet-learnings.yaml",
)

# Directories recreated on each run.
RUN_DIRS = ("current", "history")


def reset_agent_artifacts(project: Path, *, dry_run: bool = False) -> list[str]:
    root = agent_dir(project)
    if not root.is_dir():
        return [f"(skip) no .agent at {root}"]

    removed: list[str] = []
    for name in EXPLORATION_FILES:
        path = root / name
        if path.is_file():
            removed.append(str(path.relative_to(project)))
            if not dry_run:
                path.unlink()

    for dirname in RUN_DIRS:
        path = root / dirname
        if path.is_dir():
            removed.append(str(path.relative_to(project)) + "/")
            if not dry_run:
                shutil.rmtree(path, ignore_errors=True)

    return removed


def main() -> None:
    parser = argparse.ArgumentParser(description="Purge exploration artifacts from project .agent/")
    parser.add_argument("--project", required=True, help="Path to target project (e.g. ../content-manager)")
    parser.add_argument("--dry-run", action="store_true", help="List what would be removed")
    args = parser.parse_args()

    project = Path(args.project).resolve()
    items = reset_agent_artifacts(project, dry_run=args.dry_run)
    if not items:
        print("Nothing to remove.")
        return
    prefix = "Would remove" if args.dry_run else "Removed"
    for item in items:
        print(f"{prefix}: {item}")


if __name__ == "__main__":
    main()
